spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
            
      routes:
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path= /api/accessoriesProducts/getAllAccessoriesProduct
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path= /api/accessoriesProducts/getAccessoriesProductById/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path= /api/accessoriesProducts/getAccessoriesByType/type/**
        
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path= /api/accessoriesProducts/getAccessoriesByTypeAndId/type/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path= /api/accessoriesProducts/getAccessoriesBySuitable/suitableFor/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path= /api/accessoriesProducts/add
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/accessoriesProducts/addMultipleProducts
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/accessoriesProducts/setQuantity/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/beauty/getAllBeautyProducts
        
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/beauty/getBeautyById/**
            
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/beauty/add
            
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/beauty/addMultipleBeautyProducts
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/beauty/setQuantity/**
        
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/fashionProducts/getAllProducts
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/fashionProducts/getProductsById/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/fashionProducts/getProductsByType/type/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/fashionProducts/getProductsByTypeAndId/type/** 
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/fashionProducts/getProductsBySuitable/suitableFor/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/fashionProducts/getSuitableProductsById/suitableFor/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/fashionProducts/getProductsByGenderAndType/suitablefor/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/fashionProducts/getSuitableProductsByTypeAndId/suitablefor/**
        
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/fashionProducts/setQuantity/**
                   
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/fashionProducts/add
         
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/fashionProducts/addMultipleProducts
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/electronicsProducts/getAllElectronics
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/electronicsProducts/getElectronicsByType/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/electronicsProducts/getElectronicsByTypeAndId/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/electronicsProducts/getElectronicsById/**
        
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/electronicsProducts/setQuantity/**           
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/electronicsProducts/add
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/electronicsProducts/addMultipleElectronics
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/footWear/getAllFootWear
        
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/footWear/getFootWearById/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/footWear/getFootWearByType/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/footWear/getFootWearByTypeAndId/type/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/footWear/getFootWearBySuitable/suitableFor/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/footWear/setQuantity/**
        
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/footWear/add
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/footWear/addMultipleFootWear 
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/Toys/getAllToys
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/Toys/getToysById/**
        
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/Toys/setQuantity/**
          
         
          
          
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/Toys/add
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/Toys/addMultipleToys
               
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/accessoriesProducts/getAccessoriesBySellerName/sellerName/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/accessoriesProducts/updateSellerProducts/**
         
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/beauty/getBeautyBySellerName/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/beauty/updateSellerProducts/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/electronicsProducts/getElectronicsBySellerName/sellerName/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/electronicsProducts/updateSellerProducts/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/fashionProducts/getSellerProducts/sellerName/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/fashionProducts/updateSellerProducts/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/footWear/getFootWearBySellerName/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/footWear/updateSellerProducts/**
       
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/Toys/getToysBySellerName/sellerName/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/Toys/updateSellerProducts/**
       
        - id : order-service
          uri : http://localhost:8300
          predicates:
          - Method=GET
          - Path=/api/cart/getProducts
          filters:
          - AuthenticationFilter
          
        - id : order-service
          uri : http://localhost:8300
          predicates:
          - Method=GET
          - Path=/api/cart/getByUserName/**
          filters:
          - AuthenticationFilter
          
        - id : order-service
          uri : http://localhost:8300
          predicates:
          - Method=GET
          - Path=/api/cart/getByProductId/**
          filters:
          - AuthenticationFilter
          
        - id : order-service
          uri : http://localhost:8300
          predicates:
          - Method=GET
          - Path=/api/cart/getProductCategoryAndProductId/**
          filters:
          - AuthenticationFilter
          
        - id : order-service
          uri : http://localhost:8300
          predicates:
          - Method=GET
          - Path=/api/cart/**
          filters:
          - AuthenticationFilter
          
        - id : order-service
          uri : http://localhost:8300
          predicates:
          - Method=DELETE
          - Path=/api/cart/deleteProductInCartByProductId/**
          filters:
          - AuthenticationFilter
          
        - id : order-service
          uri : http://localhost:8300
          predicates:
          - Method=DELETE
          - Path=/api/cart/DeleteAllItemsInCart
          filters:
          - AuthenticationFilter
          
        - id : order-service
          uri : http://localhost:8300
          predicates:
          - Method=DELETE
          - Path=/api/cart/deleteProductInCart/**
          filters:
          - AuthenticationFilter
          
        - id : order-service
          uri : http://localhost:8300
          predicates:
          - Method=POST
          - Path=/api/createOrder/**
          filters:
          - AuthenticationFilter
          
        - id : order-service
          uri : http://localhost:8300
          predicates:
          - Method=GET
          - Path=/api/getOrders/**
          filters:
          - AuthenticationFilter
          
        - id : order-service
          uri : http://localhost:8300
          predicates:
          - Method=GET
          - Path=/api/getOrders
          filters:
          - AuthenticationFilter
          
        - id : order-service
          uri : http://localhost:8300
          predicates:
          - Method=POST
          - Path=/api/cart/addMutlipleProducts
          filters:
          - AuthenticationFilter
        
        - id : payment-service
          uri : http://localhost:8083
          predicates:
          - Method=POST
          - Path=/api/add
          filters:
          - AuthenticationFilter
          
        - id : payment-service
          uri : http://localhost:8083
          predicates:
          - Method=GET
          - Path=/api/userBalance/getUserBalance
          filters:
          - AuthenticationFilter
          
        - id : payment-service
          uri : http://localhost:8083
          predicates:
          - Method=GET
          - Path=/api/userBalance/getBalanceByUserName/**
          filters:
          - AuthenticationFilter
          
        - id : payment-service
          uri : http://localhost:8083
          predicates:
          - Method=GET
          - Path=/api/userBalance/getDetails
          filters:
          - AuthenticationFilter
          
#        - id : user-service
#          uri : http://localhost:8400
#          predicates:
#          - Method=GET
#          - Path=/getUserName/**
#          filters:
#          - AuthenticationFilter
#        
#        - id : user-service
#          uri : http://localhost:8400
#          predicates:
#          - Method=GET
#          - Path=/getUserByContactNumber/**
#          filters:
#          - AuthenticationFilter
#          
#        - id : user-service
#          uri : http://localhost:8400
#          predicates:
#          - Method=GET
#          - Path=/getUserByMail/**
#          filters:
#          - AuthenticationFilter
#          
#        - id : user-service
#          uri : http://localhost:8400
#          predicates:
#          - Method=GET
#          - Path=/getUserInfo/**
#          filters:
#          - AuthenticationFilter
          
        - id : user-service
          uri : http://localhost:8400
          predicates:
          - Method=PUT
          - Path=/updateUserData/**
          filters:
          - AuthenticationFilter
       
        
      
          
        
