spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000/"
            allowedMethods: "*"
            allowedHeaders: "*"
#            allowCredentials: true
            maxAge: 3600


          