spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            
      routes:
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path= /api/accessoriesProducts/getAllAccessoriesProduct
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path= /api/accessoriesProducts/getAccessoriesProductById/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path= /api/accessoriesProducts/getAccessoriesByType/type/**
        
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path= /api/accessoriesProducts/getAccessoriesByTypeAndId/type/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path= /api/accessoriesProducts/getAccessoriesBySuitable/suitableFor/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path= /api/accessoriesProducts/add
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/accessoriesProducts/addMultipleProducts
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/accessoriesProducts/setQuantity/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/beauty/getAllBeautyProducts
        
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/beauty/getBeautyById/**
            
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/beauty/add
            
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/beauty/addMultipleBeautyProducts
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/beauty/setQuantity/**
        
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/fashionProducts/getAllProducts
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/fashionProducts/getProductsById/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/fashionProducts/getProductsByType/type/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/fashionProducts/getProductsByTypeAndId/type/** 
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/fashionProducts/getProductsBySuitable/suitableFor/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/fashionProducts/getSuitableProductsById/suitableFor/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/fashionProducts/getProductsByGenderAndType/suitablefor/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/fashionProducts/getSuitableProductsByTypeAndId/suitablefor/**
        
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/fashionProducts/setQuantity/**
                   
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/fashionProducts/add
         
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/fashionProducts/addMultipleProducts
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/electronicsProducts/getAllElectronics
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/electronicsProducts/getElectronicsByType/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/electronicsProducts/getElectronicsByTypeAndId/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/electronicsProducts/getElectronicsById/**
        
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/electronicsProducts/setQuantity/**           
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/electronicsProducts/add
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/electronicsProducts/addMultipleElectronics
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/footWear/getAllFootWear
        
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/footWear/getFootWearById/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/footWear/getFootWearByType/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/footWear/getFootWearByTypeAndId/type/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/footWear/getFootWearBySuitable/suitableFor/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/footWear/setQuantity/**
        
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/footWear/add
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/footWear/addMultipleFootWear 
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/Toys/getAllToys
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/Toys/getToysById/**
        
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/Toys/setQuantity/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/Toys/add
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/Toys/addMultipleToys
               
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/accessoriesProducts/getAccessoriesBySellerName/sellerName/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/accessoriesProducts/updateSellerProducts/**
         
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/beauty/getBeautyBySellerName/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/beauty/updateSellerProducts/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/electronicsProducts/getElectronicsBySellerName/sellerName/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/electronicsProducts/updateSellerProducts/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/fashionProducts/getSellerProducts/sellerName/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/fashionProducts/updateSellerProducts/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/footWear/getFootWearBySellerName/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/footWear/updateSellerProducts/**
       
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/Toys/getToysBySellerName/sellerName/**
          
        - id : inventory-service
          uri : http://localhost:8200
          predicates:
          - Path=/api/Toys/updateSellerProducts/**
       
        - id : order-service
          uri : http://localhost:8300
          predicates:
          - Path=/api/cart/getProducts
         
        - id : order-service
          uri : http://localhost:8300
          predicates:
          - Path=/api/cart/getByUserName/**
          
        - id : order-service
          uri : http://localhost:8300
          predicates:
          - Path=/api/cart/getByProductId/**
          
        - id : order-service
          uri : http://localhost:8300
          predicates:
          - Path=/api/cart/getProductCategoryAndProductId/**
          
        - id : order-service
          uri : http://localhost:8300
          predicates:
          - Path=/api/cart/**
          
        - id : order-service
          uri : http://localhost:8300
          predicates:
          - Path=/api/cart/deleteProductInCartByProductId/**
          
        - id : order-service
          uri : http://localhost:8300
          predicates:
          - Path=/api/cart/DeleteAllItemsInCart
          
        - id : order-service
          uri : http://localhost:8300
          predicates:
          - Path=/api/cart/deleteProductInCart/**
          
        - id : order-service
          uri : http://localhost:8300
          predicates:
          - Path=/api/createOrder/**
          
        - id : order-service
          uri : http://localhost:8300
          predicates:
          - Path=/api/getOrders/**
          
        - id : order-service
          uri : http://localhost:8300
          predicates:
          - Path=/api/getOrders
          
        - id : order-service
          uri : http://localhost:8300
          predicates:
          - Path=/api/cart/addMutlipleProducts
          
        - id : order-service
          uri : http://localhost:8300
          predicates:
          - Path=/api/cart/add
        
        - id : order-service
          uri : http://localhost:8300
          predicates:
          - Path=/api/address/addAddress
          
        - id : order-service
          uri : http://localhost:8300
          predicates:
          - Path=/api/address/getAllAddress/**
          
        - id : order-service
          uri : http://localhost:8300
          predicates:
          - Path=/api/address/deleteAddressById/**
          
        - id : order-service
          uri : http://localhost:8300
          predicates:
          - Path=/api/address/GetAddressById/**  
        
        - id : payment-service
          uri : http://localhost:8083
          predicates:
          - Path=/api/userBalance/getUserBalance
          
        - id : payment-service
          uri : http://localhost:8083
          predicates:
          - Path=/api/userBalance/getBalanceByUserName/**
          
        - id : payment-service
          uri : http://localhost:8083
          predicates:
          - Path=/api/userBalance/getDetails
          
        - id : payment-service
          uri : http://localhost:8083
          predicates:
          - Path=/api/add
          
        - id : user-service
          uri : http://localhost:8400
          predicates:
          - Path=/getUserName/**

        - id : user-service
          uri : http://localhost:8400
          predicates:
          - Path=/getUserByContactNumber/**
          
        - id : user-service
          uri : http://localhost:8400
          predicates:
          - Path=/getUserByMail/**
          
        - id : user-service
          uri : http://localhost:8400
          predicates:
          - Path=/getUserInfo/**
          
        - id : user-service
          uri : http://localhost:8400 
          predicates:
          - Path=/updateUserData/**
          
        - id : user-service
          uri : http://localhost:8400 
          predicates:
          - Path=/login
          
        - id : user-service
          uri : http://localhost:8400 
          predicates:
          - Path=/addUser
          
        - id : user-service
          uri : http://localhost:8400 
          predicates:
          - Path=/addSeller
       
        
      
          
        
