spring:
  cloud:
    function:
      definition: paymentProcessor
    stream:
      bindings:
        paymentProcessor-in-0 :
          destination: order-event1
        paymentProcessor-out-0:
          destination: payment-event1
server:
  port: 8083
